package sshavail

import (
	"context"
	"fmt"
	"strconv"
	"strings"
)

// ReconfigureStaticIPv4 updates the live address and persistent Debian/Ubuntu
// network config while still reachable on currentIP.
func ReconfigureStaticIPv4(ctx context.Context, currentIP, password, newIP, gateway string, prefix int) error {
	currentIP = strings.TrimSpace(currentIP)
	newIP = strings.TrimSpace(newIP)
	gateway = strings.TrimSpace(gateway)
	password = strings.TrimSpace(password)
	if currentIP == "" || newIP == "" || password == "" {
		return fmt.Errorf("sshavail: currentIP, newIP and password required")
	}
	if prefix <= 0 || prefix > 32 {
		prefix = 24
	}
	if gateway == "" {
		parts := strings.Split(newIP, ".")
		if len(parts) == 4 {
			gateway = parts[0] + "." + parts[1] + "." + parts[2] + ".1"
		}
	}

	client, err := dialRoot(ctx, currentIP, password)
	if err != nil {
		return err
	}
	defer client.Close()

	script := buildStaticIPScript(newIP, gateway, prefix)
	if err := run(client, script); err != nil {
		return fmt.Errorf("sshavail: reconfigure ipv4: %w", err)
	}
	return nil
}

func buildStaticIPScript(newIP, gateway string, prefix int) string {
	pfx := strconv.Itoa(prefix)
	var b strings.Builder
	b.WriteString("set -euo pipefail\n")
	b.WriteString("IFACE=$(ip -o link show | awk -F': ' '$2!~/lo/{print $2; exit}')\n")
	b.WriteString("test -n \"$IFACE\"\n")
	b.WriteString("CUR=$(ip -4 -o addr show dev \"$IFACE\" | awk '{print $4}' | head -1 | cut -d/ -f1 || true)\n")
	b.WriteString(fmt.Sprintf("NEW=%q\n", newIP))
	b.WriteString(fmt.Sprintf("GW=%q\n", gateway))
	b.WriteString(fmt.Sprintf("PFX=%s\n", pfx))
	b.WriteString(`
mkdir -p /etc/network/interfaces.d /etc/cloud/cloud.cfg.d
cat > /etc/network/interfaces <<EOF
auto lo
iface lo inet loopback
source /etc/network/interfaces.d/*
EOF
rm -f /etc/network/interfaces.d/*
cat > /etc/network/interfaces.d/50-static <<EOF
auto $IFACE
iface $IFACE inet static
    address $NEW/$PFX
    gateway $GW
    dns-nameservers 1.1.1.1 8.8.8.8
EOF
# cloud-init must not wipe static config on reboot
echo 'network: {config: disabled}' > /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
# NetworkManager (AlmaLinux/Rocky/CentOS/RHEL). Write profiles directly:
# an older daemon can reject profiles generated by a newer nmcli client.
if command -v nmcli >/dev/null 2>&1 || [ -d /etc/NetworkManager ]; then
  mkdir -p /etc/NetworkManager/system-connections /etc/sysconfig/network-scripts
  NM_FILE="/etc/NetworkManager/system-connections/cloud-hustle-static-${IFACE}.nmconnection"
  NM_UUID=$(sed -n 's/^uuid=//p' "$NM_FILE" 2>/dev/null | head -1 || true)
  [ -n "$NM_UUID" ] || NM_UUID=$(cat /proc/sys/kernel/random/uuid)
  cat > "$NM_FILE" <<EOF
[connection]
id=cloud-hustle-static-$IFACE
uuid=$NM_UUID
type=ethernet
interface-name=$IFACE
autoconnect=true
autoconnect-priority=100

[ipv4]
address1=$NEW/$PFX,$GW
dns=1.1.1.1;8.8.8.8;
method=manual

[ipv6]
method=disabled
EOF
  chmod 600 "$NM_FILE"
  cat > "/etc/sysconfig/network-scripts/ifcfg-${IFACE}" <<EOF
DEVICE=$IFACE
NAME=cloud-hustle-static-$IFACE
TYPE=Ethernet
ONBOOT=yes
BOOTPROTO=none
IPADDR=$NEW
PREFIX=$PFX
GATEWAY=$GW
DNS1=1.1.1.1
DNS2=8.8.8.8
EOF
fi
# Netplan (Ubuntu). Do not apply it in this SSH session: applying the new
# address would disconnect the command before the caller can see success.
if ls /etc/netplan/*.yaml >/dev/null 2>&1; then
  cat > /etc/netplan/50-static.yaml <<EOF
network:
  version: 2
  ethernets:
    $IFACE:
      addresses: [$NEW/$PFX]
      routes:
        - to: default
          via: $GW
      nameservers:
        addresses: [1.1.1.1, 8.8.8.8]
EOF
fi
# Activate only after this SSH command exits successfully. Switching the
# address synchronously tears down the session and used to look like failure
# even though the guest had already moved to the new IP.
OLD="$CUR" IFACE="$IFACE" NEW="$NEW" GW="$GW" PFX="$PFX" \
  nohup sh -c '
    sleep 2
    ip addr replace "$NEW/$PFX" dev "$IFACE"
    ip route replace default via "$GW" dev "$IFACE"
    if [ -n "$OLD" ] && [ "$OLD" != "$NEW" ]; then
      ip addr del "$OLD/$PFX" dev "$IFACE" 2>/dev/null || true
    fi
  ' </dev/null >/var/log/cloud-hustle-ip-change.log 2>&1 &
echo CHANGE_SCHEDULED
`)
	return b.String()
}
