#!/usr/bin/env bash
# Bootstrap flavors/images/network ids for portal OPENSTACK_* env.
set -euo pipefail

if [[ -f "$HOME/demo-openrc" ]]; then
  # shellcheck disable=SC1091
  source "$HOME/demo-openrc"
fi

if ! command -v openstack >/dev/null 2>&1; then
  echo "openstack CLI not in PATH; skip bootstrap"
  exit 0
fi

echo "OpenStack bootstrap for VPS portal dev..."

# Flavors matching catalog PROSTO-1 (1 vCPU, 1GB RAM, 10GB disk)
openstack flavor create --id auto --vcpus 1 --ram 1024 --disk 10 m1.small 2>/dev/null || \
  openstack flavor create --vcpus 1 --ram 1024 --disk 10 m1.small 2>/dev/null || true

NET_ID="$(openstack network list -f value -c ID -c Name | awk '$2=="private"{print $1; exit}')"
EXT_ID="$(openstack network list --external -f value -c ID | head -1)"

if [[ -z "${NET_ID:-}" ]]; then
  NET_ID="$(openstack network list -f value -c ID | head -1)"
fi

IMG_NAME="ubuntu-22.04"
if ! openstack image show "$IMG_NAME" >/dev/null 2>&1; then
  TMP="/tmp/ubuntu-22.04-server-cloudimg-amd64.img"
  if [[ ! -f "$TMP" ]]; then
    echo "Downloading Ubuntu 22.04 cloud image..."
    curl -fsSL -o "$TMP" \
      https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-amd64.img
  fi
  openstack image create "$IMG_NAME" --file "$TMP" --disk-format qcow2 --container-format bare --public
fi

OUT="$HOME/openstack-portal-dev.env"
CTRL_IP="$(hostname -I | awk '{print $1}')"
{
  echo "# Generated by bootstrap-dev.sh — merge into NL infra/docker/.env"
  echo "OPENSTACK_USE_MOCK=false"
  echo "OPENSTACK_AUTH_URL=http://${CTRL_IP}:5000/v3"
  echo "OPENSTACK_REGION=RegionOne"
  echo "OPENSTACK_USERNAME=admin"
  echo "# Set password from: snap get openstack credentials (or sunbeam credentials)"
  echo "OPENSTACK_PASSWORD=CHANGE_ME"
  echo "OPENSTACK_PROJECT_NAME=admin"
  echo "OPENSTACK_DOMAIN_NAME=Default"
  echo "OPENSTACK_INSECURE_TLS=true"
  echo "OPENSTACK_NETWORK_ID=${NET_ID:-}"
  echo "OPENSTACK_FLOATING_NETWORK_ID=${EXT_ID:-}"
  echo "OPENSTACK_PLAN_MAP=11111111-1111-1111-1111-111111111101:m1.small"
  echo "OPENSTACK_OS_MAP=ubuntu-22.04:${IMG_NAME}"
  echo "OPENSTACK_PROVISION_REGIONS=nl"
} > "$OUT"

echo "Wrote $OUT"
echo "Update OPENSTACK_PASSWORD manually from: sunbeam credentials || snap get microstack"
cat "$OUT"
